### ISSUE TITLE
メールの動作確認

### ISSUE THREAD

**Issue by PharaohKJ** [jshimazu/ha4go#12]
通知用メールの動作確認を行う。

**Comment by PharaohKJ** [comment]
現状、IDとパスワードが生で埋まっているのは非常にマズイので環境変数経由などに変更するのは必須。

・・・してあった。 `dotenv-rails`でしてあった。 facebook api key と同じく、.env で指定しないといけないので注意。(herokuの場合は heroku config)

加藤のブランチではgmailでテストできた。

**Comment by kiyohara** [comment]
送信の仕組み自体は実装済み
関連する残件として #74 とか #69 とかがある。
