### ISSUE TITLE
仮でトップページの文言を修正する

### ISSUE THREAD

**Issue by ibexorg** [jshimazu/ha4go#19]
対「協働のまちづくり事業」のプレゼン資料作成のため、仮でトップページの文言を修正してください。(もうしわけないです）
文言は
「課題を深く知る市民とシビックテックの情報交換サイト、はじめました。」くらいでおねがいします。

**Comment by PharaohKJ** [comment]
49637d4b6e0efbdde13bc785af845f19978e26a4
で対応しました。スクショを slack に貼ったので確認してください。

問題なかったら close をお願いします。

**Comment by ibexorg** [comment]
問題ありません。助かりました。
仮なので、後でデザインを検討するタイミングで、ここの文言も考えたいと思います。
