### ISSUE TITLE
Torige デザインコメント

### ISSUE THREAD

**Issue by kiyohara** [jshimazu/ha4go#21]
Torige さんのデザインレビュー
思った事をどんどんコメントするスレッド

**Comment by kiyohara** [comment]
評価に使うサイトはこれ

http://ha4go-demo.herokuapp.com/

**Comment by kiyohara** [comment]
一覧の段階で「フェーズ」がわかるようにして欲しい

**Comment by kiyohara** [comment]
フェーズは一つの軸にシーケンシャルに進むモノではないように思う。
属性毎にアイコンがあるようなものではないか。
「人募集中」タグがついてるかどうか、とか。

**Comment by ibexorg** [comment]
同種のサイトとして参考までに
https://cf.yokohama.localgood.jp/

**Comment by kiyohara** [comment]
Issue として作成してもらう方式にシフトしたので本 Issue はクローズする
