### ISSUE TITLE
横幅をせまくするとメニューが反応しない

### ISSUE THREAD

**Issue by PharaohKJ** [jshimazu/ha4go#25]
横幅をせまくすると表示されるメニューが反応しない

**Comment by izawa** [comment]
対応します。

**Comment by izawa** [comment]
対応したつもり。ご確認ください。

**Comment by PharaohKJ** [comment]
6d5f2294b97fe4b7d57973ae49183b6f4df166ae
で修正を確認ありがとうございました。
