### ISSUE TITLE
進捗タグを作成し、一覧で見られるようにする

### ISSUE THREAD

**Issue by PharaohKJ** [jshimazu/ha4go#30]
進捗タグを作成し、一覧で見られるようにする

**Comment by ibexorg** [comment]
議論
企画・設計
プロトタイプ作成
ユーザテスト
運用
改善・改修

参加者募集
デザイナー募集
エンジニア募集

すみません、遅くなりました。
文字数は揃えたほうが良いならば、また少し考えます。

**Comment by PharaohKJ** [comment]
わかりました。いったんいれてみましょう。

**Comment by PharaohKJ** [comment]
とりあえず見られるのでクローズ。複数つけられないのは別issueで。
