### ISSUE TITLE
db:migrateがエラーで止まる

### ISSUE THREAD

**Issue by izawa** [jshimazu/ha4go#36]
rake db:migrate すると、まだ存在しない user_session table を drop しにいってエラーで止まる。

**Comment by PharaohKJ** [comment]
$B$9$_$^$;$s$$$^$N$H$3$m0lH/L\$O(B  `rake db:reset` $B$7$F$/$@$5$$!#(B

**Comment by izawa** [comment]
解読班、はやく！

**Comment by izawa** [comment]
rake db:migrate すると、各migration の up と change がファイル名順(つまりは日付順)に実行されます。
rake db:drop すると、各migration の down が実行されます。
というわけで、drop table は change ではなくて down として定義してやらないといけません。

**Comment by PharaohKJ** [comment]
1st Versionでは `rake db:reset` してください。
downのprを受けたのでいったんcloseします。

**Comment by izawa** [comment]
rake db:setup で動くようになるのが理想で、これでそうなったはず。 (「rake db:create」「rake db:migrate」「rake db:seed」を実行することとおなじ)
