### ISSUE TITLE
プロフィール編集のできることで未選択で追加できる(他)

### ISSUE THREAD

**Issue by ibexorg** [jshimazu/ha4go#51]
1.未入力で追加できてしまう。
2.同じ”できること”を追加できる。(ex:Javaを２つ以上登録)
細かいですが..

**Comment by ibexorg** [comment]
ちなみに、2つ以上同じ"できること"で登録すると、メンバーの検索で登録した人がダブってでてきます。

**Comment by PharaohKJ** [comment]
実装メモ) 追加したときに lowercase→半角to全角してコンペして、マッチした場合、マスタ側nameで保存する。無かったらユーザーの入力したままに新規追加する。

**Comment by PharaohKJ** [comment]
> ちなみに、2つ以上同じ"できること"で登録すると、メンバーの検索で登録した人がダブってでてきます。
これはまぁDB的にそうなるだろうので作るところでカバーします。
