### ISSUE TITLE
"プロジェクトを編集する"画面で戻るが必要

### ISSUE THREAD

**Issue by ibexorg** [jshimazu/ha4go#55]
現在は作成ボタンしかありませんが、他と同じように戻るアンカーが必要？
※他のIssueにあったかと思いますが「プロジェクトを編集」ではなく、今のところ「課題を編集」ですね。

**Comment by PharaohKJ** [comment]
戻る作成、課題を編集、双方とも対応。
ついでに、戻る、テキストリンクの部分をボタンに変更
