### ISSUE TITLE
"課題をみる"(最初のトップページ）の並びの課題のシェアボタンのリンク先が間違ってる？

### ISSUE THREAD

**Issue by ibexorg** [jshimazu/ha4go#57]
トップページと課題一覧ではおそらくURLが間違ってる？
![screenshot from 2015-08-30 11-56-09](https://cloud.githubusercontent.com/assets/7151911/9565507/4173c91a-4f0e-11e5-867e-53822f6059a4.png)

**Comment by PharaohKJ** [comment]
herokuで試して問題なさそう。
